/**
 * Static fault catalog lookup, joined by decimal code.
 *
 * src/fault-analysis.json is generated by scripts/fault-analysis-report.js from
 * the Feishu fault table + nexis-config, and carries per-code desc / topic /
 * producer / upstream / downstream / sd rationale. We index it by `code_dec`
 * (decimal string) to enrich decoded runtime alarms.
 */
import analysis from '../fault-analysis.json';

const byCodeDec = new Map();
for (const f of analysis.faults || []) {
  if (f.code_dec != null) byCodeDec.set(String(f.code_dec), f);
}

/**
 * @param {string|number|bigint} codeRaw decimal code
 * @returns catalog entry or null
 */
export function lookupFault(codeRaw) {
  if (codeRaw == null) return null;
  return byCodeDec.get(String(codeRaw)) || null;
}

export function catalogStats() {
  return { count: byCodeDec.size, generatedAt: analysis.generated_at };
}
