/**
 * BEV decoder — wire-level protobuf parser for neo_perception messages.
 *
 * MCAP files generated by record2mcap embed only the top-level proto
 * descriptor without imports, so protobufjs cannot resolve nested types.
 * We parse the relevant subset of fields directly from the wire format.
 *
 * Schemas covered:
 *   - neodrive.global.neo_perception.BevMap (lanes/lines/objects)
 *   - neodrive.global.neo_perception.OccResult (occupancy grid)
 *
 * All coordinates are in vehicle frame: x=forward, y=left, z=up, meters.
 */

// -----------------------------------------------------------------------
//  Wire-level reader utilities
// -----------------------------------------------------------------------

function readVarint(buf, pos) {
  let result = 0, shift = 0;
  while (pos < buf.length) {
    const b = buf[pos];
    result += (b & 0x7F) * Math.pow(2, shift);
    pos++;
    if ((b & 0x80) === 0) { return [result, pos]; }
    shift += 7;
    if (shift > 63) { break; }
  }
  return [result, pos];
}

/**
 * Iterate fields in a length-delimited protobuf message.
 * Calls cb(fieldNum, wireType, value, view) per field.
 * For wire-type 2, value is a Uint8Array slice.
 * For wire-type 0, value is the varint as Number.
 * For wire-type 1, value is the offset; caller reads via DataView.
 * For wire-type 5, value is the offset; caller reads via DataView.
 */
function forEachField(buf, view, cb) {
  let pos = 0;
  while (pos < buf.length) {
    const [tag, p1] = readVarint(buf, pos);
    pos = p1;
    const fieldNum = tag >>> 3;
    const wireType = tag & 0x07;

    if (wireType === 0) {
      const [val, p2] = readVarint(buf, pos);
      pos = p2;
      cb(fieldNum, wireType, val, null);
    } else if (wireType === 1) {
      const off = buf.byteOffset + pos;
      cb(fieldNum, wireType, off, view);
      pos += 8;
    } else if (wireType === 2) {
      const [len, p2] = readVarint(buf, pos);
      pos = p2;
      const sub = buf.subarray(pos, pos + len);
      cb(fieldNum, wireType, sub, view);
      pos += len;
    } else if (wireType === 5) {
      const off = buf.byteOffset + pos;
      cb(fieldNum, wireType, off, view);
      pos += 4;
    } else {
      break;
    }
  }
}

function readDouble(view, byteOffset) {
  return view.getFloat64(byteOffset, true);
}

// Read a packed repeated varint field: returns array of numbers.
function readPackedVarintsAsInts(buf) {
  const out = [];
  let pos = 0;
  while (pos < buf.length) {
    const [v, p] = readVarint(buf, pos);
    out.push(v);
    pos = p;
  }
  return out;
}

// Read packed repeated fixed32 (uint32) - little-endian.
function readPackedFixed32(buf, view) {
  const out = [];
  for (let i = 0; i + 4 <= buf.length; i += 4) {
    out.push(view.getUint32(buf.byteOffset + i, true));
  }
  return out;
}

// -----------------------------------------------------------------------
//  Message parsers
// -----------------------------------------------------------------------

// Point2D: 1=x (double), 2=y (double)
function parsePoint2D(buf, view) {
  const out = { x: 0, y: 0 };
  forEachField(buf, view, (fn, wt, val) => {
    if (wt !== 1) { return; }
    if (fn === 1) { out.x = readDouble(view, val); }
    else if (fn === 2) { out.y = readDouble(view, val); }
  });
  return out;
}

// Point3D: 1=x, 2=y, 3=z
function parsePoint3D(buf, view) {
  const out = { x: 0, y: 0, z: 0 };
  forEachField(buf, view, (fn, wt, val) => {
    if (wt !== 1) { return; }
    if (fn === 1) { out.x = readDouble(view, val); }
    else if (fn === 2) { out.y = readDouble(view, val); }
    else if (fn === 3) { out.z = readDouble(view, val); }
  });
  return out;
}

// Polyline: 1=point (repeated Point2D)
function parsePolyline(buf, view) {
  const points = [];
  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 2) { points.push(parsePoint2D(val, view)); }
  });
  return points;
}

// OrientedBox3D: 1=center (Point3D), 2=size (Point3D), 3=heading (double)
function parseOrientedBox3D(buf, view) {
  const out = { center: { x: 0, y: 0, z: 0 }, size: { x: 0, y: 0, z: 0 }, heading: 0 };
  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 2) { out.center = parsePoint3D(val, view); }
    else if (fn === 2 && wt === 2) { out.size = parsePoint3D(val, view); }
    else if (fn === 3 && wt === 1) { out.heading = readDouble(view, val); }
  });
  return out;
}

// Id: 1=id (uint32)
function parseId(buf, view) {
  let id = 0;
  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 0) { id = val; }
  });
  return id;
}

// Line (only fields we render):
//   1=id, 2=main_type (enum), 4=line_color (enum), 9=geometry (Polyline),
//   12=line_style (enum)
export const LineMainType = {
  CENTER: 0, BOUNDARY: 1, CURB: 2, STOP: 3, SPEED_BUMP: 4,
  DIVERSION: 5, VIRTUAL: 6, UNKNOWN: 7,
};
export const LineColor = { WHITE: 0, YELLOW: 1, UNKNOWN: 2 };
export const LineStyle = { DASH: 0, SOLID: 1, UNKNOWN: 2 };

function parseLine(buf, view) {
  const out = {
    id: 0,
    mainType: LineMainType.UNKNOWN,
    color: LineColor.UNKNOWN,
    style: LineStyle.UNKNOWN,
    points: [],
  };
  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 2) { out.id = parseId(val, view); }
    else if (fn === 2 && wt === 0) { out.mainType = val; }
    else if (fn === 4 && wt === 0) { out.color = val; }
    else if (fn === 9 && wt === 2) { out.points = parsePolyline(val, view); }
    else if (fn === 12 && wt === 0) { out.style = val; }
  });
  return out;
}

// Lane (only fields we render):
//   1=id, 2=lane_type, 3=turn_direction, 6=center_line, 7=left_boundary,
//   8=right_boundary, 12=primary_lane (bool/varint)
function parseLane(buf, view) {
  const out = {
    id: 0,
    laneType: 7, // UNKNOWN
    turnDirection: 3, // UNKNOWN
    primaryLane: false,
    centerLine: null,
    leftBoundary: null,
    rightBoundary: null,
  };
  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 2) { out.id = parseId(val, view); }
    else if (fn === 2 && wt === 0) { out.laneType = val; }
    else if (fn === 3 && wt === 0) { out.turnDirection = val; }
    else if (fn === 6 && wt === 2) { out.centerLine = parseLine(val, view); }
    else if (fn === 7 && wt === 2) { out.leftBoundary = parseLine(val, view); }
    else if (fn === 8 && wt === 2) { out.rightBoundary = parseLine(val, view); }
    else if (fn === 12 && wt === 0) { out.primaryLane = !!val; }
  });
  return out;
}

// Object (only fields we render):
//   1=id, 2=object_type (enum), 6=geometry (OrientedBox3D),
//   7=vx, 8=vy, 9=vz (double)
export const ObjectType = {
  UNKNOWN: 0, VEHICLE: 1, PEDESTRIAN: 2, CYCLIST: 3,
  LARGEVEHICLE: 4, SOD: 5, PARKING_SPACE: 6, BICYCLE: 7,
};

function parseObject(buf, view) {
  const out = {
    id: 0,
    objectType: ObjectType.UNKNOWN,
    geometry: { center: { x: 0, y: 0, z: 0 }, size: { x: 0, y: 0, z: 0 }, heading: 0 },
    vx: 0, vy: 0, vz: 0,
  };
  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 2) { out.id = parseId(val, view); }
    else if (fn === 2 && wt === 0) { out.objectType = val; }
    else if (fn === 6 && wt === 2) { out.geometry = parseOrientedBox3D(val, view); }
    else if (fn === 7 && wt === 1) { out.vx = readDouble(view, val); }
    else if (fn === 8 && wt === 1) { out.vy = readDouble(view, val); }
    else if (fn === 9 && wt === 1) { out.vz = readDouble(view, val); }
  });
  return out;
}

// StaticObject (subset):
//   1=id, 2=object_type, 4=geometry (OrientedBox3D)
function parseStaticObject(buf, view) {
  const out = {
    id: 0,
    objectType: ObjectType.UNKNOWN,
    geometry: { center: { x: 0, y: 0, z: 0 }, size: { x: 0, y: 0, z: 0 }, heading: 0 },
  };
  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 2) { out.id = parseId(val, view); }
    else if (fn === 2 && wt === 0) { out.objectType = val; }
    else if (fn === 4 && wt === 2) { out.geometry = parseOrientedBox3D(val, view); }
  });
  return out;
}

// BevMap fields:
//   1=timestamp, 2=lanes, 3=all_lines, 4=road_boundaries, 5=stop_lines,
//   6=objects, 13=static_objects
/**
 * @param {Uint8Array} bytes
 * @returns {{timestamp: number, lanes: Array, allLines: Array, roadBoundaries: Array,
 *   stopLines: Array, objects: Array, staticObjects: Array}}
 */
export function parseBevMap(bytes) {
  const buf = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  const out = {
    timestamp: 0,
    lanes: [],
    allLines: [],
    roadBoundaries: [],
    stopLines: [],
    objects: [],
    staticObjects: [],
  };

  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 1) { out.timestamp = readDouble(view, val); }
    else if (fn === 2 && wt === 2) { out.lanes.push(parseLane(val, view)); }
    else if (fn === 3 && wt === 2) { out.allLines.push(parseLine(val, view)); }
    else if (fn === 4 && wt === 2) { out.roadBoundaries.push(parseLine(val, view)); }
    else if (fn === 5 && wt === 2) { out.stopLines.push(parseLine(val, view)); }
    else if (fn === 6 && wt === 2) { out.objects.push(parseObject(val, view)); }
    else if (fn === 13 && wt === 2) { out.staticObjects.push(parseStaticObject(val, view)); }
  });

  return out;
}

// -----------------------------------------------------------------------
//  OccResult
// -----------------------------------------------------------------------

export const OccupancyType = {
  BACKGROUND: 0, DRIVEABLE_SURFACE: 1, VEGETATION: 2, BUILDINGS: 3,
  VEHICLE: 4, CYCLIST: 5, PEDESTRIAN: 6, OTHER_SOD: 7, SOD: 8,
  CURB: 9, OTHERS: 10,
};

export const OccupancyStatus = {
  UNKNOWN: 0, FREE: 1, OCCUPIED: 2, FILTER: 3,
};

/**
 * Parse OccResult into a renderable structure.
 *
 * Two encoding versions exist:
 *   - v1 (dense): `dimensions` + `occupancy_status` (uint8 flat array) +
 *     optional `occupancy_type`.
 *   - v2 (sparse): `occ_value` packed uint32 array; each value packs
 *     [grid_idx (high bits) | label | status (low bits)] using the bit
 *     counts in `index_bit_count`, `label_bit_count`, `status_bit_count`.
 *
 * Returns a unified intermediate representation: list of occupied cells
 * with (gridX, gridY, gridZ, status, type), plus grid metadata.
 *
 * @param {Uint8Array} bytes
 */
export function parseOccResult(bytes) {
  const buf = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  const out = {
    timestamp: 0,
    lowerBound: { x: 0, y: 0, z: 0 },
    upperBound: { x: 0, y: 0, z: 0 },
    resolution: { x: 1, y: 1, z: 1 },
    dimensions: [],
    occupancyStatus: null,   // Uint8Array (dense) or null
    occupancyType: null,
    msgVersion: '',
    indexBitCount: 0,
    labelBitCount: 0,
    statusBitCount: 0,
    occValues: null,         // Uint32Array (sparse) or null
  };

  forEachField(buf, view, (fn, wt, val) => {
    if (fn === 1 && wt === 1) { out.timestamp = readDouble(view, val); }
    else if (fn === 3 && wt === 2) { out.lowerBound = parsePoint3D(val, view); }
    else if (fn === 4 && wt === 2) { out.upperBound = parsePoint3D(val, view); }
    else if (fn === 5 && wt === 2) { out.resolution = parsePoint3D(val, view); }
    else if (fn === 6 && wt === 2) {
      // packed repeated int32
      out.dimensions.push(...readPackedVarintsAsInts(val));
    }
    else if (fn === 6 && wt === 0) {
      // non-packed int32 (older encoders)
      out.dimensions.push(val);
    }
    else if (fn === 9 && wt === 2) { out.occupancyStatus = new Uint8Array(val); }
    else if (fn === 10 && wt === 2) { out.occupancyType = new Uint8Array(val); }
    else if (fn === 12 && wt === 2) {
      out.msgVersion = new TextDecoder().decode(val);
    }
    else if (fn === 13 && wt === 0) { out.indexBitCount = val; }
    else if (fn === 14 && wt === 0) { out.labelBitCount = val; }
    else if (fn === 15 && wt === 0) { out.statusBitCount = val; }
    else if (fn === 16 && wt === 2) {
      // packed repeated uint32
      out.occValues = new Uint32Array(readPackedFixed32(val, view));
    }
  });

  return out;
}

/**
 * Decode sparse OccResult into an array of {gx, gy, gz, status, type}.
 * For dense encoding, decodes the full 3D array (could be large; caller
 * should be aware).
 *
 * @returns {Array<{gx:number, gy:number, gz:number, status:number, type:number}>}
 */
export function expandOccCells(occResult) {
  const cells = [];
  const dims = occResult.dimensions;
  if (dims.length < 3) { return cells; }
  const [dx, dy, dz] = dims;

  if (occResult.occValues && occResult.occValues.length > 0
      && occResult.indexBitCount > 0) {
    // Sparse: occ_value packs [idx(high) | label(mid) | status(low)]
    const idxBits = occResult.indexBitCount;
    const labelBits = occResult.labelBitCount;
    const statusBits = occResult.statusBitCount;
    const statusMask = (1 << statusBits) - 1;
    const labelMask = (1 << labelBits) - 1;
    const labelShift = statusBits;
    const idxShift = statusBits + labelBits;
    for (const v of occResult.occValues) {
      const status = v & statusMask;
      const type = (v >>> labelShift) & labelMask;
      const idx = v >>> idxShift;
      // Index layout: assume row-major (z, y, x) or (x, y, z)?
      // Conventionally for BEV apps, idx = ((x * dy) + y) * dz + z
      // We try x-major: idx -> gx, gy, gz where idx = (gx*dy + gy)*dz + gz
      const gz = idx % dz;
      const remain = Math.floor(idx / dz);
      const gy = remain % dy;
      const gx = Math.floor(remain / dy);
      if (gx < dx && gy < dy && gz < dz) {
        cells.push({ gx, gy, gz, status, type });
      }
    }
  } else if (occResult.occupancyStatus && occResult.occupancyStatus.length > 0) {
    // Dense: status[(gx*dy + gy)*dz + gz]
    const status = occResult.occupancyStatus;
    const type = occResult.occupancyType || null;
    const total = dx * dy * dz;
    for (let i = 0; i < total && i < status.length; i++) {
      const s = status[i];
      if (s === OccupancyStatus.UNKNOWN || s === OccupancyStatus.FREE) {
        continue; // only emit occupied cells to keep the array small
      }
      const gz = i % dz;
      const remain = Math.floor(i / dz);
      const gy = remain % dy;
      const gx = Math.floor(remain / dy);
      cells.push({
        gx, gy, gz,
        status: s,
        type: type ? type[i] : 0,
      });
    }
  }

  return cells;
}

// -----------------------------------------------------------------------
//  Schema name helpers
// -----------------------------------------------------------------------

const BEV_TOPIC_SCHEMAS = new Set([
  'neodrive.global.neo_perception.BevMap',
]);

const OCC_TOPIC_SCHEMAS = new Set([
  'neodrive.global.neo_perception.OccResult',
]);

export function isBevMapSchema(schemaName) {
  return BEV_TOPIC_SCHEMAS.has(schemaName);
}

export function isOccResultSchema(schemaName) {
  return OCC_TOPIC_SCHEMAS.has(schemaName);
}
